# Airport Traffic Performance Analysis  January 2025 vs January 2026 Using MySQL

In [450]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [451]:
%sql mysql://root:root@localhost:3306/airport_traffic

In [452]:
%config SqlMagic.style = 'PLAIN_COLUMNS'

## Data Understanding

In [453]:
%sql SELECT * FROM airport_traffic_2025 LIMIT 10;

 * mysql://root:***@localhost:3306/airport_traffic
10 rows affected.

,YEAR,MONTH_NUM,MONTH_MON,FLT_DATE,APT_ICAO,APT_NAME,STATE_NAME,FLT_DEP_1,FLT_ARR_1,FLT_TOT_1,FLT_DEP_IFR_2,FLT_ARR_IFR_2,FLT_TOT_IFR_2
0,2025,01,JAN,2025-01-01,LATI,Tirana,Albania,64,62,126,,,
1,2025,01,JAN,2025-01-01,UDYZ,Yerevan,Armenia,57,54,111,,,
2,2025,01,JAN,2025-01-01,LOWG,Graz,Austria,7,6,13,,,
3,2025,01,JAN,2025-01-01,LOWI,Innsbruck,Austria,24,25,49,,,
4,2025,01,JAN,2025-01-01,LOWK,Klagenfurt,Austria,2,0,2,,,
5,2025,01,JAN,2025-01-01,LOWL,Linz,Austria,2,2,4,,,
6,2025,01,JAN,2025-01-01,LOWS,Salzburg,Austria,17,19,36,,,
7,2025,01,JAN,2025-01-01,LOWW,Vienna,Austria,253,233,486,253,233,486
8,2025,01,JAN,2025-01-01,EBAW,Antwerp,Belgium,4,3,7,,,
9,2025,01,JAN,2025-01-01,EBBR,Brussels,Belgium,216,203,419,216,203,419

In [454]:
%sql SELECT * FROM airport_traffic_2026 LIMIT 10;

 * mysql://root:***@localhost:3306/airport_traffic
10 rows affected.

,YEAR,MONTH_NUM,MONTH_MON,FLT_DATE,APT_ICAO,APT_NAME,STATE_NAME,FLT_DEP_1,FLT_ARR_1,FLT_TOT_1,FLT_DEP_IFR_2,FLT_ARR_IFR_2,FLT_TOT_IFR_2
0,2026,01,JAN,2026-01-01,LATI,Tirana,Albania,67,70,137,,,
1,2026,01,JAN,2026-01-01,UDYZ,Yerevan,Armenia,54,55,109,,,
2,2026,01,JAN,2026-01-01,LOWG,Graz,Austria,7,6,13,,,
3,2026,01,JAN,2026-01-01,LOWI,Innsbruck,Austria,21,23,44,,,
4,2026,01,JAN,2026-01-01,LOWK,Klagenfurt,Austria,5,2,7,,,
5,2026,01,JAN,2026-01-01,LOWL,Linz,Austria,4,5,9,,,
6,2026,01,JAN,2026-01-01,LOWS,Salzburg,Austria,25,25,50,,,
7,2026,01,JAN,2026-01-01,LOWW,Vienna,Austria,279,255,534,279,254,533
8,2026,01,JAN,2026-01-01,EBAW,Antwerp,Belgium,5,5,10,,,
9,2026,01,JAN,2026-01-01,EBBR,Brussels,Belgium,224,211,435,224,211,435

## DATA CLEANING

Are there missing airport names?

In [455]:
%%sql
SELECT *
FROM airport_traffic_2025
WHERE apt_name IS NULL;

 * mysql://root:***@localhost:3306/airport_traffic
0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [456]:
%%sql
SELECT *
FROM airport_traffic_2026
WHERE apt_name IS NULL;

 * mysql://root:***@localhost:3306/airport_traffic
0 rows affected.

Empty DataFrame
Columns: []
Index: []

Are there duplicate records?

In [457]:
%%sql
SELECT apt_icao,
       flt_date,
       COUNT(*)
FROM airport_traffic_2025
GROUP BY apt_icao,
         flt_date
HAVING COUNT(*) > 1;

 * mysql://root:***@localhost:3306/airport_traffic
0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [458]:
%%sql
SELECT apt_icao,
       flt_date,
       COUNT(*)
FROM airport_traffic_2026
GROUP BY apt_icao,
         flt_date
HAVING COUNT(*) > 1;

 * mysql://root:***@localhost:3306/airport_traffic
0 rows affected.

Empty DataFrame
Columns: []
Index: []

Check invalid flight values.

In [459]:
%%sql
SELECT *
FROM airport_traffic_2025
WHERE flt_tot_1 < 0;

 * mysql://root:***@localhost:3306/airport_traffic
0 rows affected.

Empty DataFrame
Columns: []
Index: []

In [460]:
%%sql
SELECT *
FROM airport_traffic_2026
WHERE flt_tot_1 < 0;

 * mysql://root:***@localhost:3306/airport_traffic
0 rows affected.

Empty DataFrame
Columns: []
Index: []

## Exploratory Analysis (Basic SQL)

How many airports exist?

In [461]:
%sql SELECT COUNT(DISTINCT apt_icao) FROM airport_traffic_2025;

 * mysql://root:***@localhost:3306/airport_traffic
1 rows affected.

   COUNT(DISTINCT apt_icao)
0                       326

Total flights in 2025?

In [462]:
%sql SELECT SUM(flt_tot_1) FROM airport_traffic_2025;

 * mysql://root:***@localhost:3306/airport_traffic
1 rows affected.

  SUM(flt_tot_1)
0         309805

Total flights in 2026?

In [463]:
%sql SELECT SUM(flt_tot_1) FROM airport_traffic_2026;

 * mysql://root:***@localhost:3306/airport_traffic
1 rows affected.

  SUM(flt_tot_1)
0        1170605

Top 10 airports by traffic

In [464]:
%%sql
SELECT apt_name,
       SUM(flt_tot_1) total_flights
FROM airport_traffic_2025
GROUP BY apt_name
ORDER BY total_flights DESC
LIMIT 10;

 * mysql://root:***@localhost:3306/airport_traffic
10 rows affected.

                     apt_name total_flights
0                    Istanbul         11001
1           London - Heathrow         10169
2   Paris - Charles-de-Gaulle          9926
3        Amsterdam - Schiphol          9719
4            Madrid - Barajas          9017
5                   Frankfurt          7817
6                   Barcelona          7020
7            Rome - Fiumicino          6412
8                      Munich          5762
9  Istanbul - Sabiha GÃ¶kÃ§en          5353

## Intermediate SQL Analysis

Which states have highest traffic?

In [465]:
%%sql
SELECT state_name,
       SUM(flt_tot_1) total_flights
FROM airport_traffic_2025
GROUP BY state_name
ORDER BY total_flights DESC;

 * mysql://root:***@localhost:3306/airport_traffic
42 rows affected.

                     state_name total_flights
0                         Spain         42923
1                United Kingdom         38073
2                        France         32007
3                       Germany         28616
4                         Italy         25369
5                      TÃ¼rkiye         22276
6                        Norway         12434
7                   Netherlands         10364
8                      Portugal          9221
9                   Switzerland          9159
10                       Poland          8974
11                       Greece          6896
12                      Austria          6179
13                      Belgium          6077
14                      Morocco          5499
15                      Ireland          5377
16                       Sweden          4395
17                      Denmark          4367
18                      Finland          3086
19                      Hungary          2721
20               Czech Republic          2546
21                      Romania          2437
22                       Israel          2396
23                       Serbia          1639
24                       Cyprus          1528
25                     Bulgaria          1373
26                      Albania          1351
27                   Luxembourg          1311
28                      Georgia          1295
29                        Malta          1277
30                       Latvia          1274
31                      Iceland          1174
32                    Lithuania          1143
33                      Armenia          1064
34                      Croatia           968
35                      Estonia           707
36                      Moldova           667
37  Republic of North Macedonia           465
38                     Slovenia           354
39       Bosnia and Herzegovina           289
40                     Slovakia           289
41                   Montenegro           245

Monthly traffic trend

In [466]:
%%sql
SELECT month_mon,
       SUM(flt_tot_1) total_flights
FROM airport_traffic_2025
GROUP BY month_mon
ORDER BY MIN(month_num);

 * mysql://root:***@localhost:3306/airport_traffic
1 rows affected.

  month_mon total_flights
0       JAN        309805

Top 5 airports in each state

In [467]:
%%sql
SELECT state_name,
       apt_name,
       SUM(flt_tot_1) flights
FROM airport_traffic_2025
GROUP BY state_name,
         apt_name
ORDER BY flights DESC;

 * mysql://root:***@localhost:3306/airport_traffic
326 rows affected.

         state_name                   apt_name flights
0          TÃ¼rkiye                   Istanbul   11001
1    United Kingdom          London - Heathrow   10169
2            France  Paris - Charles-de-Gaulle    9926
3       Netherlands       Amsterdam - Schiphol    9719
4             Spain           Madrid - Barajas    9017
..              ...                        ...     ...
321           Spain                    Logrono       3
322           Spain                    Cordoba       2
323           Spain       Palma - Son San Juan       2
324          Latvia                    Liepaja       0
325           Spain                     Burgos       0

[326 rows x 3 columns]

States above average traffic

In [468]:
%%sql
SELECT state_name,
       SUM(flt_tot_1) flights
FROM airport_traffic_2025
GROUP BY state_name
HAVING SUM(flt_tot_1) >
(
    SELECT AVG(total_flights)
    FROM
    (
      SELECT SUM(flt_tot_1) total_flights
      FROM airport_traffic_2025
      GROUP BY state_name
    ) x
);

 * mysql://root:***@localhost:3306/airport_traffic
11 rows affected.

        state_name flights
0           France   32007
1          Germany   28616
2            Italy   25369
3      Netherlands   10364
4           Norway   12434
5           Poland    8974
6         Portugal    9221
7            Spain   42923
8      Switzerland    9159
9         TÃ¼rkiye   22276
10  United Kingdom   38073

# Advanced SQL

CTE - Which airports handled more than 100,000 flights?

In [469]:
%%sql
WITH AirportTraffic AS
(
    SELECT apt_name,
           SUM(flt_tot_1) flights
    FROM airport_traffic_2025
    GROUP BY apt_name
)
SELECT *
FROM AirportTraffic
WHERE flights > 100000;

 * mysql://root:***@localhost:3306/airport_traffic
0 rows affected.

Empty DataFrame
Columns: []
Index: []

Window Function - Rank All Airports

In [470]:
%%sql
SELECT apt_name,
       SUM(flt_tot_1) flights,
       RANK() OVER
       (
          ORDER BY SUM(flt_tot_1) DESC
       ) airport_rank
FROM airport_traffic_2025
GROUP BY apt_name;

 * mysql://root:***@localhost:3306/airport_traffic
326 rows affected.

                      apt_name flights  airport_rank
0                     Istanbul   11001             1
1            London - Heathrow   10169             2
2    Paris - Charles-de-Gaulle    9926             3
3         Amsterdam - Schiphol    9719             4
4             Madrid - Barajas    9017             5
..                         ...     ...           ...
321                    Logrono       3           321
322                    Cordoba       2           323
323       Palma - Son San Juan       2           323
324                    Liepaja       0           325
325                     Burgos       0           325

[326 rows x 3 columns]

Window Function - Dense Rank by State

In [471]:
%%sql
SELECT state_name,
       SUM(flt_tot_1) flights,
       DENSE_RANK() OVER
       (
           ORDER BY SUM(flt_tot_1) DESC
       ) state_rank
FROM airport_traffic_2025
GROUP BY state_name;

 * mysql://root:***@localhost:3306/airport_traffic
42 rows affected.

                     state_name flights  state_rank
0                         Spain   42923           1
1                United Kingdom   38073           2
2                        France   32007           3
3                       Germany   28616           4
4                         Italy   25369           5
5                      TÃ¼rkiye   22276           6
6                        Norway   12434           7
7                   Netherlands   10364           8
8                      Portugal    9221           9
9                   Switzerland    9159          10
10                       Poland    8974          11
11                       Greece    6896          12
12                      Austria    6179          13
13                      Belgium    6077          14
14                      Morocco    5499          15
15                      Ireland    5377          16
16                       Sweden    4395          17
17                      Denmark    4367          18
18                      Finland    3086          19
19                      Hungary    2721          20
20               Czech Republic    2546          21
21                      Romania    2437          22
22                       Israel    2396          23
23                       Serbia    1639          24
24                       Cyprus    1528          25
25                     Bulgaria    1373          26
26                      Albania    1351          27
27                   Luxembourg    1311          28
28                      Georgia    1295          29
29                        Malta    1277          30
30                       Latvia    1274          31
31                      Iceland    1174          32
32                    Lithuania    1143          33
33                      Armenia    1064          34
34                      Croatia     968          35
35                      Estonia     707          36
36                      Moldova     667          37
37  Republic of North Macedonia     465          38
38                     Slovenia     354          39
39       Bosnia and Herzegovina     289          40
40                     Slovakia     289          40
41                   Montenegro     245          41

Window Function - Running Total

In [472]:
%%sql
SELECT flt_date,
       SUM(flt_tot_1) daily_flights,
       SUM(SUM(flt_tot_1))
       OVER(ORDER BY flt_date)
       running_total
FROM airport_traffic_2025
GROUP BY flt_date;

 * mysql://root:***@localhost:3306/airport_traffic
9 rows affected.

     flt_date daily_flights running_total
0  2025-01-01         33357         33357
1  2025-01-02         41196         74553
2  2025-01-03         43164        117717
3  2025-01-04         38837        156554
4  2025-01-05         40583        197137
5  2025-01-06         41380        238517
6  2025-01-07         36608        275125
7  2025-01-08         34333        309458
8  2025-01-09           347        309805

Arrival vs Departure Ratio

In [473]:
%%sql
SELECT apt_name,
       SUM(flt_dep_1) AS total_departures,
       SUM(flt_arr_1) AS total_arrivals,
       ROUND(SUM(flt_arr_1) / NULLIF(SUM(flt_dep_1), 0), 3) AS arr_dep_ratio
FROM airport_traffic_2025
GROUP BY apt_name
ORDER BY arr_dep_ratio DESC;

 * mysql://root:***@localhost:3306/airport_traffic
326 rows affected.

                  apt_name total_departures total_arrivals arr_dep_ratio
0                  Logrono                1              2         2.000
1            Angers-MarcÃ©                3              4         1.333
2                   Gerona               81            103         1.272
3          Agen-La Garenne                8             10         1.250
4    Saint-Nazaire-Montoir               12             15         1.250
..                     ...              ...            ...           ...
321                  Sligo                2              1         0.500
322     Valencia - Requena                3              1         0.333
323               Sabadell               38             12         0.316
324                Liepaja                0              0          None
325                 Burgos                0              0          None

[326 rows x 4 columns]

## Year-over-Year Analysis

Total Flights : 2025 vs 2026

In [474]:
%%sql
SELECT '2025' year,
       SUM(flt_tot_1) flights
FROM airport_traffic_2025

UNION ALL

SELECT '2026',
       SUM(flt_tot_1)
FROM airport_traffic_2026;

 * mysql://root:***@localhost:3306/airport_traffic
2 rows affected.

   year  flights
0  2025   309805
1  2026  1170605

Airport-Level Year-over-Year Comparison (FIXED)

In [475]:
%%sql
SELECT
    t25.apt_name,
    SUM(t25.flt_tot_1) flights_2025,
    SUM(t26.flt_tot_1) flights_2026
FROM airport_traffic_2025 t25
JOIN airport_traffic_2026 t26
ON t25.apt_icao = t26.apt_icao
GROUP BY t25.apt_name;

 * mysql://root:***@localhost:3306/airport_traffic
326 rows affected.

                 apt_name flights_2025 flights_2026
0                  Tirana        41881        38925
1                 Yerevan        32984        28773
2                    Graz         6665         6894
3               Innsbruck        17577        18378
4              Klagenfurt         2480         2052
..                    ...          ...          ...
321         Angers-MarcÃ©          182          408
322                Burgos            0          118
323               Logrono           66          142
324     Salamanca Matalan          130          408
325  Palma - Son San Juan            2            2

[326 rows x 3 columns]

State-Level Year-over-Year Comparison

In [476]:
%%sql

WITH State2025 AS (
    SELECT state_name,
           SUM(flt_tot_1) AS flights_2025
    FROM airport_traffic_2025
    GROUP BY state_name
),
State2026 AS (
    SELECT state_name,
           SUM(flt_tot_1) AS flights_2026
    FROM airport_traffic_2026
    GROUP BY state_name
)

SELECT s25.state_name,
       s25.flights_2025,
       s26.flights_2026,
       (s26.flights_2026 - s25.flights_2025) AS flight_change,
       ROUND(
           (s26.flights_2026 - s25.flights_2025)
           / NULLIF(s25.flights_2025, 0) * 100,
           2
       ) AS growth_pct
FROM State2025 s25
JOIN State2026 s26
     ON s25.state_name = s26.state_name
ORDER BY growth_pct DESC;

 * mysql://root:***@localhost:3306/airport_traffic
42 rows affected.

,state_name,flights_2025,flights_2026,flight_change,growth_pct
0,Slovakia,289,1856,1567,542.21
1,Moldova,667,3354,2687,402.85
2,Israel,2396,11550,9154,382.05
3,Denmark,4367,18779,14412,330.02
4,Georgia,1295,5555,4260,328.96
5,Estonia,707,3032,2325,328.85
6,Slovenia,354,1510,1156,326.55
7,Romania,2437,10388,7951,326.26
8,Ireland,5377,22900,17523,325.89
9,Norway,12434,51739,39305,316.11
10,Poland,8974,37040,28066,312.75
11,Republic of North Macedonia,465,1918,1453,312.47
12,Sweden,4395,18016,13621,309.92
13,Finland,3086,12554,9468,306.80
14,TÃ¼rkiye,22276,90242,67966,305.11
15,Morocco,5499,22247,16748,304.56
16,Czech Republic,2546,10282,7736,303.85
17,Serbia,1639,6587,4948,301.89
18,Bosnia and Herzegovina,289,1153,864,298.96
19,Lithuania,1143,4434,3291,287.93
20,Malta,1277,4914,3637,284.81
21,Germany,28616,109643,81027,283.15
22,Switzerland,9159,35058,25899,282.77
23,Bulgaria,1373,5227,3854,280.70
24,Belgium,6077,23049,16972,279.28
25,Greece,6896,25712,18816,272.85
26,France,32007,118789,86782,271.13
27,Croatia,968,3588,2620,270.66
28,Cyprus,1528,5627,4099,268.26
29,Montenegro,245,892,647,264.08
30,Spain,42923,156130,113207,263.74
31,Hungary,2721,9873,7152,262.84
32,Austria,6179,22255,16076,260.17
33,Luxembourg,1311,4716,3405,259.73
34,United Kingdom,38073,136079,98006,257.42
35,Italy,25369,90394,65025,256.32
36,Portugal,9221,32693,23472,254.55
37,Latvia,1274,4350,3076,241.44
38,Netherlands,10364,35179,24815,239.43
39,Iceland,1174,3779,2605,221.89
40,Albania,1351,4325,2974,220.13
41,Armenia,1064,3197,2133,200.47